language: go
go:
- 1.11.x
addons:
  apt:
    packages:
    - debhelper
    - fakeroot
    - bash-completion
env:
  global:
  - V=1
before_script:
- make bootstrap
- make artifacts
script:
- make
after_success:
- bash <(curl -s https://codecov.io/bash) -t "$CODECOV_TOKEN" || echo "Codecov did
  not collect coverage reports"
notifications:
  email: false
stage: Github Release
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: adacQ8yOfKLTxEHY7R56kqGNL25Zw5il1sfxd9NE9Vr0w2ggQN30Jr2OqsTqdNJvDnU5EwqyvZ1ZyRbitKE3byLQY1rpt/JOagxi26xFtwrsc2h9XFNp7mDWGpRAM9QVjYb13x4TnFGHk4SNDOn/3meFV63rls28oQdBKgANozZkVmv4rsQw1lG6oKHA+tFC4x8BCZ7GTbzEleAWXU2XEm+CnovAHl4vNHGheeIjZmhYgia0M/7LLMBa9FIZizlaebZhOqXjZipBafgIVsjYJgI8Kdaxe682HHXe/g1FM3+KBMUr6oWoZ0XYSi7bz1gH9RYYstaGh2zpsxZhmzC60b95wWDPGSIKwv3Z6HOZk5HRqO092mNlplM15QcNmNe/hzKmUlo8hzG+C54mV1crdD799eezjZi9vTr+OZT0+SL1IUQXH7UZHwevp02RF8jNGJzLwi8bJYOZephbNegoQ6hpu9l+jEYdTKOjRJR4Ese1wA54WkemCouk21A6jXqyGfLL+bHApEY0GTDfh+UUfJkyF+x/2TE9Y5/DZ4BVcYXvvIOREDDB5W4JzmPRalem9ampJpTofVEMEAVmL1+XyFE6P9B6mm5sdtlbWOT1UqyFgeAA06UmA72xExwJTSgKr2WemaIAJPPCnRTvyqV8eAgBor5izEZyCxXXtpKI0nM=
  file_glob: true
  file: .travis-releases/*
  on:
    repo: smallstep/certificates
    tags: true
